import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/providers/Provider";
import { Toaster } from 'sonner';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
        <Provider>
          {children}
          <Toaster position="top-right" duration={1000}/>
        </Provider>
      </body>
    </html>
  );
}
